// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package config

// Injectors from wire.go:

func initializeConfigTest(path string) (Configuration, error) {
	configuration, err := NewConfig(path)
	if err != nil {
		return Configuration{}, err
	}
	return configuration, nil
}
