// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/challenge/payment-processor/internal/app"
	"github.com/challenge/payment-processor/internal/pkg/commom/config"
	"github.com/challenge/payment-processor/internal/pkg/commom/logging"
	"github.com/challenge/payment-processor/internal/pkg/infra/http"
	"github.com/challenge/payment-processor/internal/pkg/infra/redis"
	"github.com/challenge/payment-processor/internal/pkg/infra/security"
	"github.com/challenge/payment-processor/internal/pkg/instrumentation/info"
	"github.com/challenge/payment-processor/internal/pkg/instrumentation/metrics"
	"github.com/challenge/payment-processor/internal/pkg/processor"
	"github.com/challenge/payment-processor/internal/pkg/processor/api"
	"github.com/challenge/payment-processor/internal/pkg/webserver"
)

// Injectors from wire.go:

func initializeConfig(path string) (config.Configuration, error) {
	configuration, err := config.NewConfig(path)
	if err != nil {
		return config.Configuration{}, err
	}
	return configuration, nil
}

func initializeAppender(configuration config.Configuration) (logging.FileAppender, error) {
	fileAppender := logging.NewFileAppender(configuration)
	return fileAppender, nil
}

func initializeApp(configuration config.Configuration) (*app.PaymentProcessorApp, error) {
	redisDB := config.NewRedisDB(configuration)
	loggingLevels := config.NewLoggingLevels(configuration)
	loggerRedisDB := logging.NewRedisDB(loggingLevels)
	dbConnection, err := redis.NewDBConnection(redisDB, loggerRedisDB)
	if err != nil {
		return nil, err
	}
	defaultCardsLoader := app.NewDefaultCardsLoader(dbConnection, redisDB)
	actorsMap := processor.NewActorsMap()
	acquirerActors := processor.NewAcquirerActors(actorsMap)
	loggerProcessor := logging.NewLoggerProcessor(loggingLevels)
	paymentProcessorService := processor.NewPaymentProcessorService(acquirerActors, loggerProcessor)
	loggerAPI := logging.NewLoggerAPI(loggingLevels)
	controller := api.NewController(paymentProcessorService, loggerAPI)
	loggerWebConfigHTTPExporter := logging.NewLoggerWebConfigHTTPExporter(loggingLevels)
	configExporterHTTP := info.NewConfigExporterHTTP(configuration, loggerWebConfigHTTPExporter)
	infoApp := info.NewApp()
	loggerWebInfoHTTPExporter := logging.NewLoggerWebInfoHTTPExporter(loggingLevels)
	appInfoExporterHTTP := info.NewAppInfoExporterHTTP(infoApp, loggerWebInfoHTTPExporter)
	loggerWebVersionHTTPExporter := logging.NewLoggerWebVersionHTTPExporter(loggingLevels)
	versionExporterHTTP := info.NewVersionExporterHTTP(infoApp, loggerWebVersionHTTPExporter)
	loggerMetricsRequestResponseTime := logging.NewMetricsRequestResponseTime(loggingLevels)
	reqResponseTime := metrics.NewReqResponseTime(configuration, loggerMetricsRequestResponseTime)
	loggerMetricsRequestCounter := logging.NewMetricsRequestCounter(loggingLevels)
	requestCounter := metrics.NewRequestCounter(configuration, loggerMetricsRequestCounter)
	loggerWebServer := logging.NewWebServer(loggingLevels)
	panicCounter := metrics.NewPanicCounter(configuration, loggerWebServer)
	loggerJWTFilter := logging.NewLoggerJWTFilter(loggingLevels)
	jwtFilter := security.NewJWTFilter(configuration, loggerJWTFilter)
	paramWebServer := webserver.NewParamWebServer(controller, configExporterHTTP, appInfoExporterHTTP, versionExporterHTTP, reqResponseTime, requestCounter, panicCounter, jwtFilter, configuration, loggerWebServer)
	webServer := webserver.NewWebServer(paramWebServer)
	loggerCardRepository := logging.NewLoggerCardRepository(loggingLevels)
	cardRepositoryRedis := processor.NewCardRepositoryRedis(dbConnection, redisDB, configuration, loggerCardRepository)
	loggerHTTP := logging.NewLoggerHTTP(loggingLevels)
	service := http.NewHTTPService(loggerHTTP)
	acquirerParameter := processor.NewAcquirerParameter(cardRepositoryRedis, service)
	stoneAcquirerWorkers := processor.NewStoneAcquirerWorkers(acquirerActors, acquirerParameter, configuration)
	cieloAcquirerWorkers := processor.NewCieloAcquirerWorkers(acquirerActors, acquirerParameter, configuration)
	logger := logging.NewLogger(loggingLevels)
	paymentProcessorApp := app.NewPaymentProcessorApp(defaultCardsLoader, webServer, stoneAcquirerWorkers, cieloAcquirerWorkers, logger)
	return paymentProcessorApp, nil
}
