{
 "title": "Requisições HTTP - Payment Processor API",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latência em milissegundo",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(challenge_payment_processor_api_http_req_response_time_bucket[1m]))",
     "legendFormat": "99p {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9, rate(challenge_payment_processor_api_http_req_response_time_bucket[1m]))",
     "legendFormat": "90p {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.5, rate(challenge_payment_processor_api_http_req_response_time_bucket[1m]))",
     "legendFormat": "50p {{instance}}"
    },
    {
     "expr": "rate(challenge_payment_processor_api_http_req_response_time_sum[1m])\n/\nrate(challenge_payment_processor_api_http_req_response_time_count[1m])",
     "legendFormat": "avg {{instance}}"
    }
   ]
  },
  {
   "title": "Pedidos de Autorização por segundo - status/endpoint/adquirente",
   "type": "graph",
   "description": "req/seg em janela de 1 minuto ",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(challenge_payment_processor_api_http_req_processed_total{url=~\"/transactions.*\"}[1m])",
     "legendFormat": "{{instance}} {{code}}  {{url}}  {{acquirer}}"
    }
   ]
  },
  {
   "title": "Total de falhas graves",
   "type": "singlestat",
   "description": "Total de falhas graves(crash com panic)",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "challenge_payment_processor_api_http_req_fail_panic_total"
    }
   ]
  },
  {
   "title": "Falha Grave",
   "type": "graph",
   "description": "Falha Grave da Applicação",
   "gridPos": { "h": 9, "w": 7, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(challenge_payment_processor_api_http_req_fail_panic_total[1h]))",
     "legendFormat": "md 1h"
    },
    {
     "expr": "challenge_payment_processor_api_http_req_fail_panic_total ",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Requisições por segundo - total",
   "type": "graph",
   "description": "req/seg em janela de 1 e 5  minutos",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(challenge_payment_processor_api_http_req_processed_total[1m])) by (instance)",
     "legendFormat": "r/s 1m {{instance}}"
    },
    {
     "expr": "sum(rate(challenge_payment_processor_api_http_req_processed_total[5m])) by (instance)",
     "legendFormat": "r/s 5m {{instance}}"
    }
   ]
  },
  {
   "title": "Versões da aplicação",
   "type": "table",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(challenge_payment_processor_api_build_info) by (version)",
     "legendFormat": "Version - {{version}}"
    },
    {
     "expr": "sum(challenge_payment_processor_api_build_info) by (revision)",
     "legendFormat": "Revision - {{revision}}"
    },
    {
     "expr": "sum(challenge_payment_processor_api_build_info) by (goversion)",
     "legendFormat": "Golang - {{goversion}}"
    },
    {
     "expr": "sum(challenge_payment_processor_api_build_info) by (branch)",
     "legendFormat": "Branch - {{branch}}"
    }
   ]
  },
  {
   "title": "Dependências da aplicação",
   "type": "table",
   "gridPos": { "h": 14, "w": 7, "x": 4, "y": 21 },
   "targets": [
    {
     "expr": "sum(go_mod_info) by (name,version)",
     "legendFormat": "{{name}} | {{version}}"
    }
   ]
  },
  {
   "title": "Requisições por segundo - status/endpoint",
   "type": "graph",
   "description": "req/seg em janela de 1 minuto",
   "gridPos": { "h": 14, "w": 13, "x": 11, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(challenge_payment_processor_api_http_req_processed_total[1m])",
     "legendFormat": "{{instance}} {{code}}  {{url}}"
    }
   ]
  }
 ]
}