// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package redis

import (
	"github.com/challenge/payment-processor/internal/pkg/commom/config"
	"github.com/challenge/payment-processor/internal/pkg/commom/logging"
)

// Injectors from wire.go:

func initializeConfigTest() (config.Configuration, error) {
	string2 := newIntegrationConfigFile()
	configuration, err := config.NewConfig(string2)
	if err != nil {
		return config.Configuration{}, err
	}
	return configuration, nil
}

func initializeRedisTest(config2 config.Configuration) (DBConnection, error) {
	redisDB := config.NewRedisDB(config2)
	loggingLevels := config.NewLoggingLevels(config2)
	loggerRedisDB := logging.NewRedisDB(loggingLevels)
	dbConnection, err := NewDBConnection(redisDB, loggerRedisDB)
	if err != nil {
		return nil, err
	}
	return dbConnection, nil
}
