swagger: "2.0"
info:
  title: "Payment Processor API"
  description: "API para processamento de transação com cartão"
  version: "1.0.0"
basePath: "/api"
tags:
- name: "Transaction"
  description: "Permite processamento de transações"
schemes:
- "http"
- "https"
produces:
  - application/json
paths:
  /transactions:
    post:
      tags:
      - "Transaction"
      summary: "Processa transação"
      description: "Processa transação com parâmetro informado"
      parameters:
      - in: "header"
        name: "X-Acquirer-ID"
        description: Identificador da Adquirente
        required: true
        type: string
        x-example: Stone
      - in: "body"
        name: "transaction"
        description: "Informações representa dados de uma transação para processamento"
        required: true
        schema:
          $ref: "#/definitions/Transaction"
      security:
        - JWTAuthorizationBearerToken: []
      responses:
        200:
          description: "Sucesso. Transação autorizada."
        400:
          $ref: "#/responses/BadRequest"
        401:
          $ref: "#/responses/Unauthorized"
        403:
          $ref: "#/responses/Forbidden"
        404:
          $ref: "#/responses/NotFound"
        500:
          $ref: "#/responses/UnexpectedError"
        503:
          $ref: "#/responses/ServiceUnavailable"
        default:
          description: "Erro inesperado no processamtno da transação."
responses:
  BadRequest:
    description: |
      Um ou mais parâmetros informados são inválidos. Pode ser gerado pela própria API ou proveniente
      da Adquirente.

      Erros possíveis da *API*:
        * Um ou Mais parâmetros não são válidos
      
      Erros possíveis da *Adquirente*:
        * Validação da Adquirente ao Processar Transação

    schema:
      $ref: "#/definitions/ParametersError"
  Unauthorized:
    description: "Erro na validação do token JWT."
  Forbidden:
    description: "Token JWT verificado, mas com credenciais sem direito de acesso."
  NotFound:
    description: |
      Recurso solicitado inexistente.
      Erros possíveis:
        * Adquirente inexistente
        * Cartão inexistente
    schema:
      $ref: "#/definitions/Error"
  UnexpectedError:
    description: "Erro inesperado no processamento da transação."
    schema:
      $ref: "#/definitions/Error"
  ServiceUnavailable:
    description: |
      Serviço temporariamente indisponível. Tente novamente mais tarde
      Erros possíveis:
        * Falha na Adquirente ao Processar Transação.
        * Erro de conexão com Adquirente. 
    schema:
      $ref: "#/definitions/Error"
      
definitions:
  Transaction:
    type: object
    description: "Informações representa dados de uma transação"
    properties:
      token:
        type: string
        description: |
          Informações do cartão criptografadas. Neste projeto de exemplo o token é encodado em base64.
          É gerado por **base64(num_cartao - cvv_cartao)** 
        example: NDQzNiA5ODQxIDM4MTIgNzQ2MCAtIDU4Mg==
      holder:
        type: string
        description: Portador.
        example: Carlos 
      brand:
        type: string
        description: Bandeira.
        example: Visa
      validity:
        type: string
        description: Validade no formato AAAA-MM.
        example: 2021-03
      total:
        type: number
        format: float
        description: Valor da compra.
        example: 900
      installments:
        type: number
        format: int64
        description: Parcelas
        example: 12
      items:
        description: Itens da compra
        type: "array"
        xml:
          name: "items"
          wrapped: true
        items:
          $ref: "#/definitions/TransactionItem"
      id:
        type: string
        description: CPF/CNPJ do vendedor
        example: 60.849.406/0001-75
      address:
        type: string
        description: Endereço do vendedor.
        example: Avenida Das Américas, 5150, Barra da Tijuca, Rio de Janeiro - RJ
      zipcode:
        type: string
        description: CEP do vendedor.
        example: 22640-102
    xml:
      name: "transaction"
  TransactionItem:
    type: object
    description: "representa dados de itens de uma transação"
    properties:
      description:
        type: string
        description: Descrição do item.
        example: Lindt
      price:
        type: number
        description: Preço do item.
        format: float
        example: 900
    xml:
      name: "item"
  Error:
    type: object
    required:
      - title
    properties:
      title:
        type: string
      detail:
        type: string
    xml:
      name: "Error"
  ParametersError:
    type: object
    description: "representa informações sobre erro de parâmetros"
    required:
      - title
    properties:
      title:
        type: string
      detail:
        type: string
      invalid-parameters:
        type: "array"
        xml:
          name: "invalid-parameters"
          wrapped: true
        items:
          $ref: "#/definitions/ParameterError"
    xml:
      name: "ParametersError"
  ParameterError:
    type: "object"
    description: "representa informações sobre erro de parâmetro"
    properties:
      name:
        type: string
      value:
        type: string
      reason:
        type: string
    xml:
      name: "ParameterError"
securityDefinitions:
   JWTAuthorizationBearerToken:
     type: apiKey
     in: header
     name: Authorization
     description: |
      Autorização da API é feita com [JWT](http://jwt.io/) token.
      Deve ser enviado header HTTP Authorization como a seguir
        ```yaml
          Authorization: Bearer <jwt_token>
        ```
      No campo abaixo para testes use o ***Exemplo:***
        ```
        Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiYXVkIjoicGF5bWVudC1wcm9jZXNzb3ItYXBpIn0.uw-8pECPeJbme82nptMI-bsP8f4GvCx9x6b_GzM5wws
        ```
      A chave JWT '***challenge***' usada nos testes e em desenvolvimento é parametrizada via 
      variáveis de ambiente. 
      Nos testes o Container Docker recebe variáveis de ambiente definidas no arquivo
      de configuração config.env.
        ```
          PROCESSOR_SECURITY_JWTKEY=challenge
        ```

      Para criar um token válido é preciso informar o atributo ***aud** = payment-processor-api*.
      ```json
      {
        "sub": "1234567890",
        "aud": "payment-processor-api"
      }
      ```

      Para verificar o token acima use a chave 'challenge' no [link](https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiYXVkIjoicGF5bWVudC1wcm9jZXNzb3ItYXBpIn0.uw-8pECPeJbme82nptMI-bsP8f4GvCx9x6b_GzM5wws).
      




